# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: 'monthly'
  open-pull-requests-limit: 99
  groups:
    # Group all GitHub Actions PRs into a single PR:
    all-github-actions:
      patterns:
        - "*"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
