on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
    - created

jobs:
  tests:
    name: Tests ${{ matrix.os }} - Node ${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 12.x
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Compile
      run: npm install && npm run compile
    - name: Run tests on Linux with xvfb-run
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - name: Run tests on Windows or macOS
      run: npm test
      if: runner.os != 'Linux'
    - name: Publish Release to VS Code Marketplace
      if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
      run: npm run publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
